[project]
name = "ri-reproducibility"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tommyrharper", email = "zeroknowledgeltd@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "anesthetic>=2.15.1",
]

[project.scripts]
ri-reproducibility = "ri_reproducibility:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
